In [1]:
import sys
import scanpy as sc
import anndata
import pandas as pd
import numpy as np
import os

data_type = 'float32'

In [2]:
import matplotlib as mpl
from matplotlib import rcParams
import matplotlib.pyplot as plt
import seaborn as sns

# silence scanpy that prints a lot of warnings
import warnings
warnings.filterwarnings('ignore')

# TPC

In [3]:
rna = anndata.read_h5ad("../TPC.h5ad")
meta = pd.read_csv('../TPC_meta.csv', index_col=0)

sc.pp.filter_cells(rna, min_genes=1)
sc.pp.filter_genes(rna, min_cells=200)

rna.obs = meta

rna.raw = rna
# convert the adata object into a dataframe which has rownames as cell ID, 
# colnames as gene names
df = pd.DataFrame(data=rna.raw.X, 
                  index=rna.raw.obs_names, 
                  columns=rna.raw.var_names)
df.head()

,LINC01409,HES4,ISG15,TTLL10,TNFRSF4,MXRA8,VWA1,MMP23B,CDK11B,AL139246.5,...,BGN,BCAP31,L1CAM,TKTL1,FLNA,F8,MT-ATP8,MT-ND4L,AC240274.1,AC007325.4
20149X1_AAACGAACACAAATAG-1,-0.331499,-0.32455,-0.504933,-0.418455,3.572244,-0.439394,0.774136,-0.36197,-0.413999,-0.122797,...,-0.523188,0.440671,-0.083365,-0.348167,0.620285,2.325588,-0.503194,0.259315,-0.286421,-0.354822
20149X1_AAACGAACAGACCTAT-1,-0.331499,-0.32455,-0.504933,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,-0.413999,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,0.574612,1.643611,-0.503194,0.521004,-0.286421,-0.354822
20149X1_AAACGCTGTAGGACCA-1,-0.331499,-0.32455,1.843142,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,-0.413999,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,1.238884,-0.521317,-0.503194,1.228002,-0.286421,-0.354822
20149X1_AAAGAACCACGTTGGC-1,-0.331499,-0.32455,-0.504933,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,-0.413999,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,1.594683,1.774002,-0.503194,1.606685,-0.286421,-0.354822
20149X1_AAAGTCCGTGGGATTG-1,3.030155,-0.32455,-0.504933,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,2.698770,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,0.555688,2.360803,-0.503194,1.088745,-0.286421,-0.354822

In [4]:
gene_df = rna.var
gene_filtered = list(gene_df[gene_df['n_cells']>0].index)
adata_filtered = df[gene_filtered]
adata_filtered.head()

,LINC01409,HES4,ISG15,TTLL10,TNFRSF4,MXRA8,VWA1,MMP23B,CDK11B,AL139246.5,...,BGN,BCAP31,L1CAM,TKTL1,FLNA,F8,MT-ATP8,MT-ND4L,AC240274.1,AC007325.4
20149X1_AAACGAACACAAATAG-1,-0.331499,-0.32455,-0.504933,-0.418455,3.572244,-0.439394,0.774136,-0.36197,-0.413999,-0.122797,...,-0.523188,0.440671,-0.083365,-0.348167,0.620285,2.325588,-0.503194,0.259315,-0.286421,-0.354822
20149X1_AAACGAACAGACCTAT-1,-0.331499,-0.32455,-0.504933,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,-0.413999,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,0.574612,1.643611,-0.503194,0.521004,-0.286421,-0.354822
20149X1_AAACGCTGTAGGACCA-1,-0.331499,-0.32455,1.843142,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,-0.413999,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,1.238884,-0.521317,-0.503194,1.228002,-0.286421,-0.354822
20149X1_AAAGAACCACGTTGGC-1,-0.331499,-0.32455,-0.504933,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,-0.413999,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,1.594683,1.774002,-0.503194,1.606685,-0.286421,-0.354822
20149X1_AAAGTCCGTGGGATTG-1,3.030155,-0.32455,-0.504933,-0.418455,-0.163379,-0.439394,-0.502717,-0.36197,2.698770,-0.122797,...,-0.523188,-0.665590,-0.083365,-0.348167,0.555688,2.360803,-0.503194,1.088745,-0.286421,-0.354822

In [5]:
adata_filtered = adata_filtered[0:-1]
merged_features = pd.merge(pd.DataFrame(rna.obs['BMI']), adata_filtered,
                           left_index=True, right_index=True)
merged_features = pd.merge(merged_features,pd.DataFrame(rna.obs['age']), 
                           left_index=True, right_index=True)
merged_features.to_csv('../TPC_data.csv')